package Views;

import Controller.LoginController;
import DAO.FuncionarioDAO;
import DTO.FuncionarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class LoginViews extends javax.swing.JFrame {

    private final LoginController controller;

    public LoginViews() {
        initComponents();
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SenhaLabel = new javax.swing.JLabel();
        LoginLabel1 = new javax.swing.JLabel();
        LoginScanner = new javax.swing.JTextField();
        EntrarButton = new javax.swing.JButton();
        SenhaScanner = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SenhaLabel.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        SenhaLabel.setText("SENHA");
        getContentPane().add(SenhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 40));

        LoginLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        LoginLabel1.setText("LOGIN");
        getContentPane().add(LoginLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, 40));

        LoginScanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginScannerActionPerformed(evt);
            }
        });
        getContentPane().add(LoginScanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 200, -1));

        EntrarButton.setText("ENTRAR");
        EntrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EntrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));
        getContentPane().add(SenhaScanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 200, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs2/Estetica automotiva.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonActionPerformed
        try {
            String login, senha;

            login = LoginScanner.getText();
            senha = SenhaScanner.getText();

            FuncionarioDTO objfuncionario = new FuncionarioDTO();
            objfuncionario.setNome_funcionario(login);
            objfuncionario.setSenha_funcionario(senha);

            FuncionarioDAO objfuncionariodao = new FuncionarioDAO();
            ResultSet rsfuncionariodao = objfuncionariodao.autenticarLogin(objfuncionario);

            if (rsfuncionariodao.next()) {
                this.controller.Entrar();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e senha incorretos!");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "LoginViews" + erro);
        }

    }//GEN-LAST:event_EntrarButtonActionPerformed

    private void LoginScannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginScannerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginScannerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginViews().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntrarButton;
    private javax.swing.JLabel LoginLabel1;
    private javax.swing.JTextField LoginScanner;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JPasswordField SenhaScanner;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
}
